server:
  port: 9320

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  config: classpath:log4j2.xml

#执行器绑定的网卡ip
localAddress: 192.168.174.128,192.168.174.10

threadPool:
  corePoolSize: 80
  maxPoolSize:  100
  queueCapacity: 5000

testData:
  tenantTotal: 1000
  invertTotal: 1000
  canCommonTotal: 100