swagger: "2.0"
info:
  title: Demo APIs
  version: "2.0"
  description: Use VSCode plugin [OpenAPI (Swagger) Editor](https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi) to edit this document.
host: localhost:8618
schemes:
  - http
  - https

paths:
  /v1/login:
    post:
      summary: 用户登录
      tags:
        - auth
      operationId: login
      produces:
        - "application/json"
      parameters:
        - name: rememberMe
          in: query
          type: boolean
          required: true
          description: 记住我
          default: true
        - name: body
          in: body
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        200:
          description: success
        400:
          description: parameter error
        500:
          description: server error
  /v1/device:
    get:
      summary: 获取压测设备信息
      description: 若云端设备没有变化，则只需要获取一次
      tags:
        - device
      operationId: getDevices
      produces:
        - "application/json"
      parameters:
        - in: query
          name: devType
          type: string
          description: 设备类型,目前支持invert、candtu-200、candtu-400、can-common
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/devicesInfo"
        400:
          description: parameter error
        500:
          description: server error
    post:
      summary: 新建设备
      description: 新建设备均匀分布在测试租户中
      tags:
        - device
      operationId: addDevices
      produces:
        - "application/json"
      parameters:
        - in: query
          name: deviceNumber
          type: integer
          description: 需要新建的设备数
        - in: query
          name: deviceType
          type: string
          description: 设备类型,目前支持invert、candtu-200、candtu-400、can-common
      responses:
        200:
          description: success
        400:
          description: parameter error
        500:
          description: server error
  /v1/pressure/start:
    get:
      summary: 开始压测
      description: 将在一段时间内尽量均匀的使设备上线，并在设置周期内尽量均匀的上报数据
      tags:
        - pressure
      operationId: pressureStart
      produces:
        - "application/json"
      parameters:
        - in: query
          name: deviceNumber
          type: integer
          description: 压测的设备数
        - in: query
          name: deviceType
          type: string
          description: 压测的设备类型
        - in: query
          name: period
          type: integer
          description: 上报数据的周期，单位：秒;设备将在此周期内尽量均匀上报数据
        - in: query
          name: topic
          type: string
          description: 上报数据类型，data、raw
        - in: query
          name: data
          type: string
          description: 上报的数据，为base64字符串
        - in: query
          name: onlineTime
          type: integer
          description: 设备上线的时限，单位：秒;设备会尽量在时限内均匀上线
      responses:
        200:
          description: success
        400:
          description: parameter error
        500:
          description: server error
  /v1/pressure/stop:
    get:
      summary: 停止压测
      description: 停止压测
      tags:
        - pressure
      operationId: pressureStop
      produces:
        - "application/json"
      responses:
        200:
          description: success
        400:
          description: parameter error
        500:
          description: server error
# common parameters
parameters:
  queryPageSize:
    name: page_size
    in: query
    type: integer
    required: false
    default: 20
    description: 每页条数
  queryCurrentPage:
    name: current_page
    in: query
    type: integer
    required: false
    default: 1
    description: 当前页

# common data structure
definitions:
  BaseResp:
    type: object
    properties:
      message:
        type: string
  OnePageData:
    type: object
    properties:
      pagination:
        type: object
        properties:
          totalSize:
            type: integer
            example: 1000
          currentPage:
            type: integer
            example: 1
          pageSize:
            type: integer
            example: 20
  LoginRequest:
    type: object
    required:
      - userName
      - password
    properties:
      userName:
        type: string
      password:
        type: string
  devicesInfo:
    type: object
    properties:
      deviceType:
        type: string
        description: 设备类型
      total:
        type: integer
        description: 该类型设备的总数
